pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/PiyushAhir21/SauceLabFramework.git'
            }
        }
        stage('Build & Test') {
            steps {
                dir('selenium-framework') { // Change to the directory containing pom.xml
                    bat 'mvn clean test'
                }
            }
            post {
                always {
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: 'selenium-framework/Advance_reporting',
                        reportFiles: 'report.html',
                        reportName: 'Extent Report'
                    ])
                }
            }
        }
        /* Uncomment this stage if you want to build a Docker image
        stage('Docker Build') {
            steps {
                script {
                    docker.build("selenium-framework:${env.BUILD_ID}")
                }
            }
        }
        */
        stage('Cleanup') {
            steps {
                cleanWs()  // Clean workspace after build
            }
        }
    }
}