pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/PiyushAhir21/SauceLabFramework.git'
            }
        }
        stage('Build & Test') {
            steps {
                sh 'mvn clean test'  // Run Maven tests
            }
            post {
                always {
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: 'target',
                        reportFiles: 'extent-report.html',
                        reportName: 'Extent Report'
                    ])
                }
            }
        }
       /* stage('Docker Build') {
            steps {
                script {
                    docker.build("selenium-framework:${env.BUILD_ID}")
                }
            }
        }*/
        stage('Cleanup') {
            steps {
                cleanWs()  // Clean workspace after build
            }
        }
    }
}